[32m2018-02-12 14:30:56.627[0m [1;30m[INFO][0m (create_and_run:80 in benchmark.py) $ Starting benchmark...
[32m2018-02-12 14:30:57.951[0m [1;30m[INFO][0m (create_and_run:82 in benchmark.py) $ The benchmark has started. pid : 28439
[32m2018-02-12 14:37:40.362[0m [1;30m[INFO][0m (create_and_run:136 in benchmark.py) $ The benchmark is ended.
[32m2018-02-12 14:37:40.363[0m [1;30m[DEBUG][0m (create_and_run:143 in benchmark.py) $ [32mremoving metric handler <RabbitMQHandler gcc(28439) (NOTSET)>[0m
[32m2018-02-12 14:37:40.365[0m [1;30m[ERROR][0m (create_and_run:149 in benchmark.py) $ [31mException has happened while removing handler form metric logger.[0m
Traceback (most recent call last):
  File "/home/dcslab/bhyoo/power-sched/bench_launcher/benchmark/benchmark.py", line 147, in create_and_run
    handler.close()
  File "/home/dcslab/bhyoo/power-sched/bench_launcher/benchmark/benchmark.py", line 214, in close
    self._channel.queue_delete(self._queue_name)
  File "/home/dcslab/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2448, in queue_delete
    self._flush_output(delete_ok_result.is_ready)
  File "/home/dcslab/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/dcslab/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
[32m2018-02-12 14:37:40.367[0m [1;30m[DEBUG][0m (create_and_run:143 in benchmark.py) $ [32mremoving metric handler <FileHandler /home/dcslab/bhyoo/power-sched/bench_launcher/experiments/solorun/gc/perf/gcc.csv (NOTSET)>[0m
